# markdown_engine/renderers/table.py
from .base import BlockRenderer
from PySide6.QtGui import QColor, QFontMetrics, QPen
from PySide6.QtCore import QRect, Qt
from ..constants import BUBBLE_PADDING, TABLE_CELL_PADDING

class TableRenderer(BlockRenderer):
    def paint(self, painter, block, msg_x, msg_y, theme, styles):
        font = styles.get_font(block.type)
        painter.setFont(font)
        fm = QFontMetrics(font)

        if not block.table_col_widths: return

        # Geometry Setup
        start_x = msg_x + BUBBLE_PADDING
        start_y = msg_y + block.y_pos
        
        col_widths = block.table_col_widths
        border_color = QColor(theme["table_border"])
        
        # 1. DRAW BACKGROUNDS & GRID
        current_y = start_y
        total_width = sum(col_widths)
        
        row_idx = 0
        
        # Helper to get height (fallback if missing)
        def get_h(idx):
            if idx < len(block.table_row_heights):
                return block.table_row_heights[idx]
            return fm.height() + (TABLE_CELL_PADDING * 2)

        # -- Header --
        header_h = get_h(row_idx)
        
        painter.setPen(QPen(border_color, 1))
        painter.setBrush(QColor(theme["table_header_bg"]))
        painter.drawRect(start_x, current_y, total_width, header_h)
        
        # Header vertical lines
        vx = start_x
        for w in col_widths:
            vx += w
            painter.drawLine(vx, current_y, vx, current_y + header_h)
        
        current_y += header_h
        row_idx += 1
        
        # -- Rows --
        for i, row in enumerate(block.table_rows):
            row_h = get_h(row_idx)
            
            bg_key = "table_row_alt" if i % 2 == 0 else "table_row_bg"
            painter.setBrush(QColor(theme[bg_key]))
            painter.drawRect(start_x, current_y, total_width, row_h)
            
            vx = start_x
            for w in col_widths:
                vx += w
                painter.drawLine(vx, current_y, vx, current_y + row_h)
            
            current_y += row_h
            row_idx += 1

        # 2. DRAW TEXT
        # LayoutLines are generated by LayoutEngine with correct wrapped positions
        painter.setPen(QColor(theme["text"]))
        
        for line in block.layout_lines:
            draw_x = line.rect.x() 
            draw_y = msg_y + line.rect.y() + line.fm.ascent()
            
            painter.drawText(draw_x, draw_y, line.text)